// Mocks generated by Mockito 5.4.4 from annotations
// in sirapro/test/services/client_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sirapro/models/visit_report.dart' as _i4;
import 'package:sirapro/services/api_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearToken() => super.noSuchMethod(
        Invocation.method(
          #clearToken,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<dynamic> get(
    String? endpoint, {
    bool? includeAuth = true,
    Map<String, String>? extraHeaders,
    bool? allowCache = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #includeAuth: includeAuth,
            #extraHeaders: extraHeaders,
            #allowCache: allowCache,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> post(
    String? endpoint, {
    Map<String, dynamic>? body,
    bool? includeAuth = true,
    Map<String, String>? extraHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #body: body,
            #includeAuth: includeAuth,
            #extraHeaders: extraHeaders,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> put(
    String? endpoint, {
    Map<String, dynamic>? body,
    bool? includeAuth = true,
    Map<String, String>? extraHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [endpoint],
          {
            #body: body,
            #includeAuth: includeAuth,
            #extraHeaders: extraHeaders,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> patch(
    String? endpoint, {
    Map<String, dynamic>? body,
    bool? includeAuth = true,
    Map<String, String>? extraHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [endpoint],
          {
            #body: body,
            #includeAuth: includeAuth,
            #extraHeaders: extraHeaders,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> delete(
    String? endpoint, {
    bool? includeAuth = true,
    Map<String, String>? extraHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
          {
            #includeAuth: includeAuth,
            #extraHeaders: extraHeaders,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> uploadFiles(
    String? endpoint, {
    required List<dynamic>? files,
    String? fileFieldName = r'photos[]',
    Map<String, String>? fields,
    bool? includeAuth = true,
    String? fileName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFiles,
          [endpoint],
          {
            #files: files,
            #fileFieldName: fileFieldName,
            #fields: fields,
            #includeAuth: includeAuth,
            #fileName: fileName,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> uploadGeotaggedPhotos(
    String? endpoint, {
    required List<_i4.GeotaggedPhoto>? photos,
    String? fileFieldName = r'photos[]',
    Map<String, String>? fields,
    bool? includeAuth = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadGeotaggedPhotos,
          [endpoint],
          {
            #photos: photos,
            #fileFieldName: fileFieldName,
            #fields: fields,
            #includeAuth: includeAuth,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> uploadGeotaggedPhotosWithProgress(
    String? endpoint, {
    required List<_i4.GeotaggedPhoto>? photos,
    String? fileFieldName = r'photos[]',
    Map<String, String>? fields,
    bool? includeAuth = true,
    _i2.UploadProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadGeotaggedPhotosWithProgress,
          [endpoint],
          {
            #photos: photos,
            #fileFieldName: fileFieldName,
            #fields: fields,
            #includeAuth: includeAuth,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}
